FROM  nvidia/cuda:12.1.0-runtime-ubuntu20.04
LABEL MAINTAINER="langchain-chatglm"

COPY agent /langchain-ChatGLM/agent

COPY chains /langchain-ChatGLM/chains

COPY configs /langchain-ChatGLM/configs

COPY loader /langchain-ChatGLM/loader

COPY models /langchain-ChatGLM/models

COPY nltk_data /langchain-ChatGLM/nltk_data

COPY textsplitter /langchain-ChatGLM/textsplitter

COPY utils /langchain-ChatGLM/utils

COPY vectorstores /langchain-ChatGLM/vectorstores

COPY api.py /langchain-ChatGLM/

COPY requirements.txt /langchain-ChatGLM/

COPY webui.py /langchain-ChatGLM/

COPY webui_st.py /langchain-ChatGLM/

WORKDIR /langchain-ChatGLM

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
RUN apt-get update -y && apt-get install python3 python3-pip curl libgl1 libglib2.0-0 -y  && apt-get clean
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3 get-pip.py 

RUN pip3 install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/ && rm -rf `pip3 cache dir`
